package: drop most of enact deps and ilib
* one less failing file node_modules/@enact/sandstone/resources/ilibmanifest.json:

before:
WARNING: com.webos.app.minimal-1.0-r0 do_package_qa: QA Issue: File /usr/palm/applications/com.webos.app.minimal/main.js.map in package com.webos.app.minimal contains reference to TMPDIR [buildpaths]
ERROR: com.webos.app.minimal-1.0-r0 do_package_qa: QA Issue: com.webos.app.minimal: /usr/palm/applications/com.webos.app.minimal/index.html is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
com.webos.app.minimal: /usr/palm/applications/com.webos.app.minimal/main.js.map is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
com.webos.app.minimal: /usr/palm/applications/com.webos.app.minimal/main.js is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
com.webos.app.minimal: /usr/palm/applications/com.webos.app.minimal/resources/ilibmanifest.json is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
com.webos.app.minimal: /usr/palm/applications/com.webos.app.minimal/node_modules/@enact/sandstone/resources/ilibmanifest.json is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination [host-user-contaminated]
ERROR: com.webos.app.minimal-1.0-r0 do_package_qa: Fatal QA errors were found, failing task.
ERROR: Logfile of failure stored in: /OE/lge/build/webos/nanbield/BUILD/work/raspberrypi4_64-webos-linux/com.webos.app.minimal/1.0/temp/log.do_package_qa.241458
ERROR: Task (/OE/lge/build/webos/nanbield/meta-lg-webos/meta-webos/recipes-webos/com.webos.app.minimal/com.webos.app.minimal.bb:do_package_qa) failed with exit code '1'

after:
WARNING: com.webos.app.minimal-1.0-r0 do_package_qa: QA Issue: File /usr/palm/applications/com.webos.app.minimal/main.js.map in package com.webos.app.minimal contains reference to TMPDIR [buildpaths]
ERROR: com.webos.app.minimal-1.0-r0 do_package_qa: QA Issue: com.webos.app.minimal: /usr/palm/applications/com.webos.app.minimal/index.html is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
com.webos.app.minimal: /usr/palm/applications/com.webos.app.minimal/main.js.map is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
com.webos.app.minimal: /usr/palm/applications/com.webos.app.minimal/main.js is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination
com.webos.app.minimal: /usr/palm/applications/com.webos.app.minimal/resources/ilibmanifest.json is owned by uid 1026, which is the same as the user running bitbake. This may be due to host contamination [host-user-contaminated]
ERROR: com.webos.app.minimal-1.0-r0 do_package_qa: Fatal QA errors were found, failing task.
ERROR: Logfile of failure stored in: /OE/lge/build/webos/nanbield/BUILD/work/raspberrypi4_64-webos-linux/com.webos.app.minimal/1.0/temp/log.do_package_qa.243542
ERROR: Task (/OE/lge/build/webos/nanbield/meta-lg-webos/meta-webos/recipes-webos/com.webos.app.minimal/com.webos.app.minimal.bb:do_package_qa) failed with exit code '1'